# Generated by Django 5.1.7 on 2025-08-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listings_bids_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
